model_params:
  name: 'VanillaAE'
  in_channels: 1
  latent_dim: 512
  out_channels: 1

exp_params:
  dataset: cycif
  data_path: "/n/pfister_lab2/Lab/enovikov/data/Artifact-CyCIF-Data-2021/Sardana-Annotations/Edward/train/data/"
  img_size: 256
  batch_size: 16 # Better to have a square number
  LR: 0.0001
  weight_decay: 0.005
  scheduler_gamma: 0.95
  kld_weight: None

trainer_params:
  gpus: 1
  max_nb_epochs: 30
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaAE_CyCIF"
  manual_seed: 1265
